#!/bin/bash

set -e

# define article paths
ARTICLE=downloads/$1
HTML_ARTICLE=${ARTICLE}-download.html
HTML_ARTICLE_CONVERTED=${ARTICLE}-conv.html
HTML_ARTICLE_PANDOC=${ARTICLE}.html
MD_ARTICLE=${ARTICLE}.md
PDF_ARTICLE=${ARTICLE}.pdf
DC_METADATA=${ARTICLE}.dc.xml

# download the article and convert it to utf8 encoding
ARTICLE_HTML_URL=
curl http://www.catholicworker.org/dorothyday/HTMLoutput.cfm?TextID=${ARTICLE} | \
    iconv -f iso-8859-1 -t utf-8  > ${HTML_ARTICLE}

# download the dublin core metadata
curl http://www.catholicworker.org/dorothyday/DublinCoreOutput.cfm?TextID=${ARTICLE} | \
   iconv -f iso-8859-1 -t utf-8  > ${DC_METADATA}

# make a copy of the originally downloaded file for conversion
cp ${HTML_ARTICLE} ${HTML_ARTICLE_CONVERTED}

# eliminate standalone P with non-breaking space
perl -i -pe 's/<[P|p]>&nbsp;<\/[P|p]>//g' ${HTML_ARTICLE_CONVERTED}

# replace <B><P align="CENTER">Foo</P> with h4
perl -i -pe 's/<b><p align="center">([^<]+)<\/p>/<h4>\1<\/h4>/i' ${HTML_ARTICLE_CONVERTED}

# replace <p align="center"><b>Funeral</b></p> with H4
perl -i -pe 's/<p align="center"><b>([^<]+)<\/b><\/p>/<h4>\1<\/h4>/i' ${HTML_ARTICLE_CONVERTED}

# replace <P><STRONG><P ALIGN="CENTER">PETER MAURIN 1877-1977</STRONG></P> with h4
perl -i -pe 's/<strong><p align="center">([^<]+)<\/strong><\/p>/<h4>\1<\/h4>/i' ${HTML_ARTICLE_CONVERTED}

# replace <B><P>The Lesson of Cuba</P> with H4
perl -i -pe 's/^<b><p>([^<]+)<\/p>/<h4>\1<\/h4>/i' ${HTML_ARTICLE_CONVERTED}

# replace <p><b>Maryfarm</b></p> with H4
perl -i -pe 's/^<p><b>([^<]+)<\/b><\/p>/<h4>\1<\/h4>/i' ${HTML_ARTICLE_CONVERTED}

# replace <P ALIGN="CENTER">* * *</P> with HR
perl -i -pe 's/<p align="center">(\* \* \*)<\/p>/- - -/i' ${HTML_ARTICLE_CONVERTED}

# cleanup orphaned </b> and </strong> tags
perl -i -pe 's/^<\/b><p>/<p>/i' ${HTML_ARTICLE_CONVERTED}
perl -i -pe 's/^<\/strong><p>/<p>/i' ${HTML_ARTICLE_CONVERTED}

# convert to markdown and remove the temporary converted file
pandoc ${HTML_ARTICLE_CONVERTED} -o ${MD_ARTICLE}
rm ${HTML_ARTICLE_CONVERTED}

# convert to html
pandoc ${MD_ARTICLE} -o ${HTML_ARTICLE_PANDOC}

#convert to pdf
pandoc ${MD_ARTICLE} -o ${PDF_ARTICLE}

