#!/bin/bash

set -e

# define article paths
ARTICLE=$1
ARTICLE_DIR=articles/${ARTICLE}
MD_ARTICLE=${ARTICLE_DIR}/${ARTICLE}.md
HTML_ARTICLE=${ARTICLE_DIR}/${ARTICLE}.html
PDF_ARTICLE=${ARTICLE_DIR}/${ARTICLE}.pdf
DOCX_ARTICLE=${ARTICLE_DIR}/${ARTICLE}.docx

# remove existing
rm -f ${PDF_ARTICLE}
rm -f ${HTML_ARTICLE}
rm -f ${DOCX_ARTICLE}

#convert to pdf
pandoc ${MD_ARTICLE} -o ${PDF_ARTICLE}

# convert to html
pandoc -s ${MD_ARTICLE} -o ${HTML_ARTICLE}

#convert to docx
pandoc ${MD_ARTICLE} -o ${DOCX_ARTICLE}


