#!/bin/bash

set -e

# get a reference to the article's markdown file 
ARTICLE=$1
MD_ARTICLE=../source/${ARTICLE}.md

# paths to use for publishing the page and related documents
ARTICLE_DIR=../www/articles/${ARTICLE}
mkdir -p ${ARTICLE_DIR}
ARTICLE_MAIN_PAGE=${ARTICLE_DIR}/index.html
ARTICLE_MARKDOWN=${ARTICLE_DIR}/${ARTICLE}.md
ARTICLE_PDF=${ARTICLE_DIR}/${ARTICLE}.pdf
ARTICLE_HTML=${ARTICLE_DIR}/${ARTICLE}.html

# define templates to use for conversions
ARTICLE_MAIN_TEMPLATE=../templates/article-main.html

# do some comversions to markdown and pdf
cp ${MD_ARTICLE} ${ARTICLE_MARKDOWN}
pandoc ${MD_ARTICLE} -o ${ARTICLE_PDF}
pandoc --smart --ascii --base-header-level=1 \
       ${MD_ARTICLE} -o ${ARTICLE_HTML}


# generate the main page for the article
pandoc -s --smart --ascii --base-header-level=2 \
       --template=${ARTICLE_MAIN_TEMPLATE} \
       --variable=article:${ARTICLE} \
       ${MD_ARTICLE} -o ${ARTICLE_MAIN_PAGE}
